joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# right_joint_position_controller:
#   type: position_controllers/JointPositionController
#   joint: A
#   pid: {p: 10.0, i: 0.0, d: 0.0}

# left_joint_position_controller:
#   type: position_controllers/JointPositionController
#   joint: B
#   pid: {p: 0.0, i: 0.0, d: 0.0}

right_joint_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: right_wheel_joint
  pid: {p: 1.0, i: 6.0, d: 0.01, i_clamp_min: -3.0, i_clamp_max: 3, antiwindup: True}

left_joint_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: left_wheel_joint
  pid: {p: 1.0, i: 6.0, d: 0.01, i_clamp_min: -3.0, i_clamp_max: 3, antiwindup: True}