!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  antiwindup: true
  d: 0.02
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      antiwindup: true
      d: 0.02
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      i: 6.0
      i_clamp_max: 3.0
      i_clamp_min: -0.0
      id: 0
      name: Default
      p: 1.0
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      state: true
      type: ''
    state: []
  i: 6.0
  i_clamp_max: 3.0
  i_clamp_min: -0.0
  p: 1.0
state: []
